# Generated by Django 5.2.7 on 2026-05-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_first_name_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='demographic_group',
            field=models.CharField(blank=True, choices=[('female4_8', 'Female 4-8'), ('male4_8', 'Male 4-8'), ('female9_13', 'Female 9-13'), ('male9_13', 'Male 9-13'), ('female14_18', 'Female 14-18'), ('male14_18', 'Male 14-18'), ('female19_30', 'Female 19-30'), ('male19_30', 'Male 19-30'), ('female31_50', 'Female 31-50'), ('male31_50', 'Male 31-50'), ('female51', 'Female 51+'), ('male51', 'Male 51+')], max_length=20, null=True),
        ),
    ]
