# Generated by Django 5.2.7 on 2026-05-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_age_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sportDaysPerWeek',
            field=models.CharField(choices=[('Sedentary', 'Sedentary'), ('Moderately Active', 'Moderately Active'), ('Active', 'Active')], default='Sedentary', max_length=30),
        ),
    ]
