# Generated by Django 5.2.7 on 2025-10-31 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='سن')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('height_cm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)], verbose_name='قد (سانتی\u200cمتر)')),
                ('weight_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(400)], verbose_name='وزن (کیلوگرم)')),
                ('education', models.CharField(max_length=100, verbose_name='تحصیلات')),
                ('job_state', models.CharField(choices=[('employed', 'شاغل'), ('student', 'محصل'), ('other', 'سایر')], max_length=10, verbose_name='وضعیت شغلی/تحصیلی')),
                ('income_bracket', models.CharField(choices=[('0-10', '0-10'), ('10-30', '10-30'), ('30-50', '30-50'), ('50-70', '50-70'), ('70-90', '70-90'), ('90+', 'more than 90')], max_length=10, verbose_name='وضعیت درآمد (میلیون)')),
                ('diet_income_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد درآمدِ تخصیص\u200cیافته به رژیم')),
                ('province', models.CharField(choices=[('azarbaijan_sharqi', 'آذربایجان شرقی'), ('azarbaijan_gharbi', 'آذربایجان غربی'), ('ardabil', 'اردبیل'), ('esfahan', 'اصفهان'), ('alborz', 'البرز'), ('ilam', 'ایلام'), ('bushehr', 'بوشهر'), ('tehran', 'تهران'), ('chaharmahal_bakhtiari', 'چهارمحال و بختیاری'), ('khorasan_jonoobi', 'خراسان جنوبی'), ('khorasan_razavi', 'خراسان رضوی'), ('khorasan_shomali', 'خراسان شمالی'), ('khuzestan', 'خوزستان'), ('zanjan', 'زنجان'), ('semnan', 'سمنان'), ('sistan_baluchestan', 'سیستان و بلوچستان'), ('fars', 'فارس'), ('qazvin', 'قزوین'), ('qom', 'قم'), ('kurdistan', 'کردستان'), ('kerman', 'کرمان'), ('kermanshah', 'کرمانشاه'), ('kohgiluyeh_boyerahmad', 'کهگیلویه و بویراحمد'), ('golestan', 'گلستان'), ('gilan', 'گیلان'), ('lorestan', 'لرستان'), ('mazandaran', 'مازندران'), ('markazi', 'مرکزی'), ('hormozgan', 'هرمزگان'), ('hamedan', 'همدان'), ('yazd', 'یزد')], max_length=32, verbose_name='استان')),
                ('marital_status', models.CharField(choices=[('single', 'مجرد'), ('married', 'متاهل')], max_length=10, verbose_name='وضعیت تاهل')),
                ('family_members', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='تعداد اعضای خانواده')),
                ('sport_days_per_week', models.CharField(choices=[('0-2', '0-2'), ('1-3', '1-3'), ('2-4', '2-4'), ('3-5', '3-5'), ('4-6', '4-6')], max_length=5, verbose_name='تعداد روزهای ورزش در هفته')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فرم دموگرافیک',
                'verbose_name_plural': 'فرم\u200cهای دموگرافیک',
                'ordering': ['-created_at'],
            },
        ),
    ]
