# Generated by Django 5.2.7 on 2025-10-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='عنوان')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای فرم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'فرم ۲',
                'verbose_name_plural': 'فرم\u200cهای ۲',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Form3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='عنوان')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای فرم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'فرم ۳',
                'verbose_name_plural': 'فرم\u200cهای ۳',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Form4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='عنوان')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت\u200cها')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای فرم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'فرم ۴',
                'verbose_name_plural': 'فرم\u200cهای ۴',
                'ordering': ['-created_at'],
            },
        ),
    ]
