# Generated by Django 5.2.7 on 2025-11-09 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_form2_form3_form4'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_meals_count', models.PositiveSmallIntegerField(choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تعداد وعده مشترک')),
                ('relationship_level', models.CharField(choices=[('family', 'خانواده'), ('friend', 'دوست'), ('colleague', 'همکار'), ('other', 'سایر')], max_length=16, verbose_name='سطح ارتباط')),
                ('influence_level', models.CharField(choices=[('none', 'هیچ'), ('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('very_high', 'خیلی زیاد')], max_length=16, verbose_name='سطح تاثیر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'فرم میانی',
                'verbose_name_plural': 'فرم\u200cهای میانی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['relationship_level'], name='Form_middle_relatio_4c47ef_idx'), models.Index(fields=['influence_level'], name='Form_middle_influen_657e99_idx'), models.Index(fields=['created_at'], name='Form_middle_created_f0a253_idx')],
            },
        ),
    ]
