# Generated by Django 5.2.7 on 2025-11-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_middleform'),
    ]

    operations = [
        migrations.AddField(
            model_name='middleform',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
