# Generated by Django 5.2.7 on 2025-11-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_middleform_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(help_text='مثلاً 101…110')),
                ('key', models.CharField(choices=[('0', '0'), ('1-2', '1-2'), ('3-4', '3-4'), ('4-6', '4-6'), ('+7', '+7')], max_length=8)),
                ('value', models.PositiveIntegerField(help_text='مقداری که از rules به\u200cدست آمد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Form2',
        ),
        migrations.AlterModelOptions(
            name='middleform',
            options={'ordering': ['-created_at'], 'verbose_name': 'افزودن همسفره', 'verbose_name_plural': 'افزودن همسفره'},
        ),
        migrations.AddIndex(
            model_name='codeselection',
            index=models.Index(fields=['code'], name='Form_codese_code_85127b_idx'),
        ),
        migrations.AddIndex(
            model_name='codeselection',
            index=models.Index(fields=['code', 'created_at'], name='Form_codese_code_e7dba2_idx'),
        ),
    ]
