# Generated by Django 5.2.7 on 2025-11-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0005_codeselection_delete_form2_alter_middleform_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeSelection',
        ),
    ]
