# Generated by Django 5.2.7 on 2025-11-20 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0006_delete_codeselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eggs', models.CharField(choices=[('0', '0'), ('1-2', '240'), ('3-4', '480'), ('4-6', '720'), ('+7', '1000')], max_length=10)),
                ('dairy', models.CharField(choices=[('0', '0'), ('1-2', '500'), ('3-4', '1000'), ('4-6', '1500'), ('+7', '2000')], max_length=10)),
                ('meat', models.CharField(choices=[('0', '0'), ('1-2', '130'), ('3-4', '260'), ('4-6', '390'), ('+7', '520')], max_length=10)),
                ('poultry', models.CharField(choices=[('0', '0'), ('1-2', '240'), ('3-4', '480'), ('4-6', '720'), ('+7', '1000')], max_length=10)),
                ('honey', models.CharField(choices=[('0', '0'), ('1-2', '100'), ('3-4', '200'), ('4-6', '300'), ('+7', '400')], max_length=10)),
                ('fish', models.CharField(choices=[('0', '0'), ('1-2', '200'), ('3-4', '400'), ('4-6', '600'), ('+7', '800')], max_length=10)),
                ('olive', models.CharField(choices=[('0', '0'), ('1-2', '50'), ('3-4', '100'), ('4-6', '200'), ('+7', '400')], max_length=10)),
                ('sugar', models.CharField(choices=[('0', '0'), ('1-2', '100'), ('3-4', '200'), ('4-6', '300'), ('+7', '400')], max_length=10)),
                ('oilsM', models.CharField(choices=[('0', '0'), ('1-2', '20'), ('3-4', '40'), ('4-6', '60'), ('+7', '100')], max_length=10)),
                ('oilsS', models.CharField(choices=[('0', '0'), ('1-2', '20'), ('3-4', '40'), ('4-6', '60'), ('+7', '100')], max_length=10)),
                ('oilolive', models.CharField(choices=[('0', '0'), ('1-2', '20'), ('3-4', '40'), ('4-6', '60'), ('+7', '100')], max_length=10)),
                ('fruit', models.CharField(choices=[('0', '0'), ('1-2', '300'), ('3-4', '600'), ('4-6', '900'), ('+7', '1200')], max_length=10)),
                ('vegetable', models.CharField(choices=[('0', '0'), ('1-2', '150'), ('3-4', '300'), ('4-6', '450'), ('+7', '600')], max_length=10)),
                ('nuts', models.CharField(choices=[('0', '0'), ('1-2', '60'), ('3-4', '120'), ('4-6', '180'), ('+7', '240')], max_length=10)),
                ('legumes', models.CharField(choices=[('0', '0'), ('1-2', '300'), ('3-4', '600'), ('4-6', '900'), ('+7', '1200')], max_length=10)),
                ('potatoes', models.CharField(choices=[('0', '0'), ('1-2', '400'), ('3-4', '800'), ('4-6', '1200'), ('+7', '1600')], max_length=10)),
                ('stimuli', models.CharField(choices=[('0', '0'), ('1-2', '40'), ('3-4', '80'), ('4-6', '120'), ('+7', '160')], max_length=10)),
                ('rice', models.CharField(choices=[('0', '0'), ('1-2', '400'), ('3-4', '800'), ('4-6', '1200'), ('+7', '1600')], max_length=10)),
                ('barley', models.CharField(choices=[('0', '0'), ('1-2', '300'), ('3-4', '600'), ('4-6', '900'), ('+7', '1200')], max_length=10)),
                ('wheat', models.CharField(choices=[('0', '0'), ('1-2', '400'), ('3-4', '800'), ('4-6', '1200'), ('+7', '1600')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فرم رژیم غذایی فعلی',
                'verbose_name_plural': 'فرم\u200cهای رژیم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='demographicform',
            name='diet_income_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد درآمدِ تخصیص\u200cیافته به رژیم'),
        ),
        migrations.AlterField(
            model_name='demographicform',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='demographicform',
            name='family_members',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='تعداد اعضای خانواده'),
        ),
        migrations.AlterField(
            model_name='demographicform',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='demographicform',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)], verbose_name='قد (سانتی\u200cمتر)'),
        ),
        migrations.AlterField(
            model_name='demographicform',
            name='income_bracket',
            field=models.CharField(blank=True, choices=[('0-10', '0-10'), ('10-30', '10-30'), ('30-50', '30-50'), ('50-70', '50-70'), ('70-90', '70-90'), ('90+', 'more than 90')], max_length=10, null=True, verbose_name='وضعیت درآمد (میلیون)'),
        ),
        migrations.AlterField(
            model_name='demographicform',
            name='job_state',
            field=models.CharField(blank=True, choices=[('employed', 'شاغل'), ('student', 'محصل'), ('other', 'سایر')], max_length=10, null=True, verbose_name='وضعیت شغلی/تحصیلی'),
        ),
        migrations.AlterField(
            model_name='demographicform',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متاهل')], max_length=10, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='demographicform',
            name='province',
            field=models.CharField(blank=True, choices=[('azarbaijan_sharqi', 'آذربایجان شرقی'), ('azarbaijan_gharbi', 'آذربایجان غربی'), ('ardabil', 'اردبیل'), ('esfahan', 'اصفهان'), ('alborz', 'البرز'), ('ilam', 'ایلام'), ('bushehr', 'بوشهر'), ('tehran', 'تهران'), ('chaharmahal_bakhtiari', 'چهارمحال و بختیاری'), ('khorasan_jonoobi', 'خراسان جنوبی'), ('khorasan_razavi', 'خراسان رضوی'), ('khorasan_shomali', 'خراسان شمالی'), ('khuzestan', 'خوزستان'), ('zanjan', 'زنجان'), ('semnan', 'سمنان'), ('sistan_baluchestan', 'سیستان و بلوچستان'), ('fars', 'فارس'), ('qazvin', 'قزوین'), ('qom', 'قم'), ('kurdistan', 'کردستان'), ('kerman', 'کرمان'), ('kermanshah', 'کرمانشاه'), ('kohgiluyeh_boyerahmad', 'کهگیلویه و بویراحمد'), ('golestan', 'گلستان'), ('gilan', 'گیلان'), ('lorestan', 'لرستان'), ('mazandaran', 'مازندران'), ('markazi', 'مرکزی'), ('hormozgan', 'هرمزگان'), ('hamedan', 'همدان'), ('yazd', 'یزد')], max_length=32, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='demographicform',
            name='sport_days_per_week',
            field=models.CharField(blank=True, choices=[('0-2', '0-2'), ('1-3', '1-3'), ('2-4', '2-4'), ('3-5', '3-5'), ('4-6', '4-6')], max_length=5, null=True, verbose_name='تعداد روزهای ورزش در هفته'),
        ),
        migrations.AlterField(
            model_name='demographicform',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(400)], verbose_name='وزن (کیلوگرم)'),
        ),
    ]
