# Generated by Django 5.2.7 on 2025-11-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0007_pwi_alter_demographicform_diet_income_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eggs', models.CharField(max_length=1)),
                ('Dairy', models.CharField(max_length=1)),
                ('Meat', models.CharField(max_length=1)),
                ('Poultry', models.CharField(max_length=1)),
                ('Honey', models.CharField(max_length=1)),
                ('Fish', models.CharField(max_length=1)),
                ('Olives', models.CharField(max_length=1)),
                ('Sugar', models.CharField(max_length=1)),
                ('OilsM', models.CharField(max_length=1)),
                ('OilsS', models.CharField(max_length=1)),
                ('Oil', models.CharField(max_length=1)),
                ('Fruit', models.CharField(max_length=1)),
                ('vegetables', models.CharField(max_length=1)),
                ('Nuts', models.CharField(max_length=1)),
                ('Legumes', models.CharField(max_length=1)),
                ('Potatoes', models.CharField(max_length=1)),
                ('Stimuli', models.CharField(max_length=1)),
                ('Rice', models.CharField(max_length=1)),
                ('Barley', models.CharField(max_length=1)),
                ('Wheat', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
        ),
        migrations.DeleteModel(
            name='Form3',
        ),
    ]
