# Generated by Django 5.2.7 on 2025-11-28 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0008_prfood_delete_form3'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferrdFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eggs', models.CharField(max_length=1)),
                ('Dairy', models.CharField(max_length=1)),
                ('Meat', models.CharField(max_length=1)),
                ('Poultry', models.CharField(max_length=1)),
                ('Honey', models.CharField(max_length=1)),
                ('Fish', models.CharField(max_length=1)),
                ('Olives', models.CharField(max_length=1)),
                ('Sugar', models.CharField(max_length=1)),
                ('OilsM', models.CharField(max_length=1)),
                ('OilsS', models.CharField(max_length=1)),
                ('Oil', models.CharField(max_length=1)),
                ('Fruit', models.CharField(max_length=1)),
                ('vegetables', models.CharField(max_length=1)),
                ('Nuts', models.CharField(max_length=1)),
                ('Legumes', models.CharField(max_length=1)),
                ('Potatoes', models.CharField(max_length=1)),
                ('Stimuli', models.CharField(max_length=1)),
                ('Rice', models.CharField(max_length=1)),
                ('Barley', models.CharField(max_length=1)),
                ('Wheat', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='Tablemates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('shared_meals_count', models.PositiveSmallIntegerField(blank=True, choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تعداد وعده مشترک')),
                ('relationship_level', models.CharField(blank=True, choices=[('family', 'خانواده'), ('friend', 'دوست'), ('colleague', 'همکار'), ('other', 'سایر')], max_length=16, null=True, verbose_name='سطح ارتباط')),
                ('influence_level', models.CharField(blank=True, choices=[('none', 'هیچ'), ('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('very_high', 'خیلی زیاد')], max_length=16, null=True, verbose_name='سطح تاثیر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'افزودن همسفره',
                'verbose_name_plural': 'افزودن همسفره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='DemographicForm',
            new_name='DemographicFormInformation',
        ),
        migrations.RenameModel(
            old_name='PrFood',
            new_name='FreeShopping',
        ),
        migrations.RenameModel(
            old_name='PWI',
            new_name='PastWeekIntake',
        ),
        migrations.DeleteModel(
            name='Form4',
        ),
        migrations.DeleteModel(
            name='MiddleForm',
        ),
        migrations.AddIndex(
            model_name='tablemates',
            index=models.Index(fields=['relationship_level'], name='Form_tablem_relatio_e53c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='tablemates',
            index=models.Index(fields=['influence_level'], name='Form_tablem_influen_204dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='tablemates',
            index=models.Index(fields=['created_at'], name='Form_tablem_created_47942f_idx'),
        ),
    ]
