# Generated by Django 5.2.7 on 2025-11-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0009_preferrdfood_tablemates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastweekintake',
            name='barley',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='dairy',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='eggs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='fish',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='fruit',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='honey',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='legumes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='meat',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='nuts',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='oilolive',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='oilsM',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='oilsS',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='olive',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='potatoes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='poultry',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='rice',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='stimuli',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='sugar',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='vegetable',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pastweekintake',
            name='wheat',
            field=models.JSONField(default=dict),
        ),
    ]
