# Generated by Django 5.2.7 on 2025-12-18 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0011_demographicforminformation_user_freeshopping_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemates',
            name='user',
        ),
        migrations.CreateModel(
            name='Tablemate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shared_meals_count', models.PositiveIntegerField(default=0)),
                ('relationship_level', models.CharField(blank=True, max_length=50, null=True)),
                ('influence_level', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablemates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tablemate',
                'verbose_name_plural': 'Tablemates',
            },
        ),
        migrations.DeleteModel(
            name='DemographicFormInformation',
        ),
        migrations.DeleteModel(
            name='Tablemates',
        ),
    ]
