# Generated by Django 5.2.7 on 2025-12-18 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0012_remove_tablemates_user_tablemate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('properties', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='pastweekintake',
            name='user',
        ),
        migrations.RemoveField(
            model_name='preferrdfood',
            name='user',
        ),
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('properties', models.JSONField(blank=True, default=dict, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_groups', to='Form.category')),
            ],
            options={
                'verbose_name': 'Food Group',
                'verbose_name_plural': 'Food Groups',
            },
        ),
        migrations.CreateModel(
            name='PastWeekIntakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('percent_usage', models.FloatField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('food_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_week_intakes', to='Form.foodgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_week_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Past Week Intake',
                'verbose_name_plural': 'Past Week Intakes',
            },
        ),
        migrations.DeleteModel(
            name='FreeShopping',
        ),
        migrations.DeleteModel(
            name='PastWeekIntake',
        ),
        migrations.DeleteModel(
            name='PreferrdFood',
        ),
    ]
