# Generated by Django 5.2.7 on 2025-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0013_category_remove_pastweekintake_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastweekintakes',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
