# Generated by Django 5.2.7 on 2025-12-25 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0014_alter_pastweekintakes_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastweekintakes',
            name='date',
        ),
        migrations.AddField(
            model_name='pastweekintakes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastweekintakes',
            name='percent_usage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
