# Generated by Django 5.2.7 on 2025-12-25 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0015_remove_pastweekintakes_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('food_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_by_users', to='Form.foodgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferred Food',
                'verbose_name_plural': 'Preferred Foods',
                'ordering': ('user_id', 'priority', 'id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'food_group'), name='uniq_preferredfood_user_foodgroup')],
            },
        ),
    ]
