# Generated by Django 5.2.7 on 2025-12-25 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0016_preferredfood'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='preferredfood',
            name='uniq_preferredfood_user_foodgroup',
        ),
    ]
