# Generated by Django 5.2.7 on 2026-01-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0017_remove_preferredfood_uniq_preferredfood_user_foodgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('code', 'id'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='foodgroup',
            options={'ordering': ('category__code', 'code', 'id'), 'verbose_name': 'Food Group', 'verbose_name_plural': 'Food Groups'},
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.IntegerField(db_index=True, default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='code',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name='foodgroup',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='uniq_foodgroup_category_code'),
        ),
    ]
