# Generated by Django 5.2.7 on 2026-01-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0019_seed_migration_data'),
    ]

    operations = [
    ]
