# Generated by Django 5.2.7 on 2026-04-28 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0021_fix_foodgroups_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeShopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('food_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_shopping_items', to='Form.foodgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_shoppings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user_id', 'id'),
            },
        ),
    ]
