# Generated by Django 5.2.7 on 2026-05-10 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0023_limitedshopping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individualism_degree', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_alignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Alignment',
                'verbose_name_plural': 'Social Alignments',
            },
        ),
    ]
