# Generated by Django 5.2.7 on 2026-05-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0024_socialalignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limitedshopping',
            options={},
        ),
        migrations.AddField(
            model_name='limitedshopping',
            name='importance_available',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='limitedshopping',
            name='importance_environment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='limitedshopping',
            name='importance_health',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='limitedshopping',
            name='importance_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='limitedshopping',
            name='position_available',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='limitedshopping',
            name='position_environment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='limitedshopping',
            name='position_health',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='limitedshopping',
            name='position_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='limitedshopping',
            name='offset_environment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='limitedshopping',
            name='offset_health',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='limitedshopping',
            name='offset_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='limitedshopping',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
