# Generated by Django 5.2.7 on 2026-05-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0025_alter_limitedshopping_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitedshopping',
            name='offset_environment',
        ),
        migrations.RemoveField(
            model_name='limitedshopping',
            name='offset_health',
        ),
        migrations.RemoveField(
            model_name='limitedshopping',
            name='offset_price',
        ),
        migrations.RemoveField(
            model_name='limitedshopping',
            name='value',
        ),
        migrations.AddField(
            model_name='limitedshopping',
            name='title',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
